# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NuGet-OrderService
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
jobs:
  publish_nuget:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: OrderService
    permissions:
      contents: read
      packages: write
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore OrderService.slnx

      - name: Build
        run: dotnet build --no-restore OrderService.slnx

      - name: Test
        run: dotnet test --no-build --verbosity normal OrderService.slnx

      - name: Build release
        run: dotnet build --configuration Release --no-restore OrderService.slnx

      - name: Pack
        run: dotnet pack --no-restore --configuration Release OrderService.slnx

      - name: Push
        run: |
          dotnet nuget push "*/bin/Release/*.nupkg" \
            --source "https://nuget.pkg.github.com/FedericoBecchi2003/index.json" \
            --skip-duplicate \
            --api-key ${{ secrets.GITHUB_TOKEN }}
